version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www/html/app
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    php:
        image: php:fpm
        volumes:
            - ./app:/var/www/html/app
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
